- name: "Update configs"
  hosts: localhost
  connection: local 
  tasks:
    - name: Copy multiple files in Ansible with different permissions
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: '.bash_aliases', dest: '~', mode: '0644'}
        - { src: '.bash_functions', dest: '~', mode: '0644'}
        - { src: '.bashrc', dest: '~', mode: '0644'}
        - { src: '.profile', dest: '~', mode: '0644'}
